services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    # Simplified healthcheck without authentication
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    ports:
      - "3100:3100"
    environment:
      - APP_PORT=3100
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017/notification_manager
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - app-network
    command: python -m src.index
    healthcheck:
      test: ["CMD", "python", "-m", "scripts.healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3

  push-worker:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017/notification_manager
    depends_on:
      - redis
      - mongo
      - app
    networks:
      - app-network
    command: python -m sim.push_worker
    deploy:
      replicas: 1

  email-worker:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=mongodb://mongo:27017/notification_manager
    depends_on:
      - redis
      - mongo
      - app
    networks:
      - app-network
    command: python -m sim.mail_worker
    deploy:
      replicas: 1

volumes:
  redis_data:
  mongo_data:

networks:
  app-network:
    driver: bridge